apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    demo: deployment
spec:
  replicas: 1
  selectors:
    matchLabels:
     app: nginx
     demo: deployment
  templates:
    metadata:
      labels:
        app: nginx
        demo: deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        Ports:
        - containerport: 80


